
/*
 * 
 */

package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jan 04 14:46:58 ARST 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "Service1", 
                  wsdlLocation = "http://200.127.43.59:8091/Service1.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class Service1 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "Service1");
    public final static QName Service1Soap12 = new QName("http://tempuri.org/", "Service1Soap12");
    public final static QName Service1Soap = new QName("http://tempuri.org/", "Service1Soap");
    static {
        URL url = null;
        try {
            url = new URL("http://200.127.43.59:8091/Service1.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://200.127.43.59:8091/Service1.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Service1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service1() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap12")
    public Service1Soap getService1Soap12() {
        return super.getPort(Service1Soap12, Service1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap12")
    public Service1Soap getService1Soap12(WebServiceFeature... features) {
        return super.getPort(Service1Soap12, Service1Soap.class, features);
    }
    /**
     * 
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public Service1Soap getService1Soap() {
        return super.getPort(Service1Soap, Service1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public Service1Soap getService1Soap(WebServiceFeature... features) {
        return super.getPort(Service1Soap, Service1Soap.class, features);
    }

}
