package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jan 04 14:46:58 ARST 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    public java.lang.String helloWorld();

    @WebResult(name = "insertItemToOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "insertItemToOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertItemToOrder")
    @ResponseWrapper(localName = "insertItemToOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertItemToOrderResponse")
    @WebMethod(action = "http://tempuri.org/insertItemToOrder")
    public int insertItemToOrder(
        @WebParam(name = "idPedido", targetNamespace = "http://tempuri.org/")
        int idPedido,
        @WebParam(name = "idArticulo", targetNamespace = "http://tempuri.org/")
        int idArticulo,
        @WebParam(name = "cantidad", targetNamespace = "http://tempuri.org/")
        double cantidad,
        @WebParam(name = "precioUnitario", targetNamespace = "http://tempuri.org/")
        double precioUnitario,
        @WebParam(name = "subtotal", targetNamespace = "http://tempuri.org/")
        double subtotal
    );

    @WebResult(name = "insertOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "insertOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrder")
    @ResponseWrapper(localName = "insertOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrderResponse")
    @WebMethod(action = "http://tempuri.org/insertOrder")
    public int insertOrder(
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fecha,
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "mail", targetNamespace = "http://tempuri.org/")
        java.lang.String mail,
        @WebParam(name = "direccion", targetNamespace = "http://tempuri.org/")
        java.lang.String direccion,
        @WebParam(name = "total", targetNamespace = "http://tempuri.org/")
        double total
    );

    @WebResult(name = "getArticulosByDescriptionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getArticulosByDescription", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticulosByDescription")
    @ResponseWrapper(localName = "getArticulosByDescriptionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticulosByDescriptionResponse")
    @WebMethod(action = "http://tempuri.org/getArticulosByDescription")
    public org.tempuri.ArrayOfArticulo getArticulosByDescription(
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        java.lang.String description
    );

    @WebResult(name = "getCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCategories", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCategories")
    @ResponseWrapper(localName = "getCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCategoriesResponse")
    @WebMethod(action = "http://tempuri.org/getCategories")
    public org.tempuri.ArrayOfCategoria getCategories();

    @WebResult(name = "getArticulosByCategoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getArticulosByCategory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticulosByCategory")
    @ResponseWrapper(localName = "getArticulosByCategoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticulosByCategoryResponse")
    @WebMethod(action = "http://tempuri.org/getArticulosByCategory")
    public org.tempuri.ArrayOfArticulo getArticulosByCategory(
        @WebParam(name = "idCategory", targetNamespace = "http://tempuri.org/")
        int idCategory
    );

    @WebResult(name = "getImageByArticuloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getImageByArticulo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetImageByArticulo")
    @ResponseWrapper(localName = "getImageByArticuloResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetImageByArticuloResponse")
    @WebMethod(action = "http://tempuri.org/getImageByArticulo")
    public byte[] getImageByArticulo(
        @WebParam(name = "idArticulo", targetNamespace = "http://tempuri.org/")
        int idArticulo
    );
}
